config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'billboards#index'

  resources :billboards do
    resources :artists
  end

  resources :artists do
    resources :songs
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :billboard
  has_many :songs
end

app/models/billboard.rb
class Billboard < ApplicationRecord

  has_many :artists
  has_many :songs

end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :billboard
  belongs_to :artist
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_billboard
  # before_action :set_song
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = @billboard.artists
  end

  def show
  end

  def new
    @artist = @billboard.artists.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @artist = @billboard.artists.new(artist_params)

    if @artist.save
      redirect_to [@billboard, @artist]
    else
      render :new
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_to [@billboard, @artist]
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to billboard_artists_path
  end

  private
    def set_billboard
      @billboard = Billboard.find(params[:billboard_id])
    end

    def set_artist
      @artist = Artist.find(params[:id])
    end

    # def set_song
    #   @song = Song
    # end  

    def artist_params
      params.require(:artist).permit(:artist_name, :song_name)
    end
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, only: [:show, :update, :edit, :destroy]
  before_action :set_artist, only: [:show, :update, :edit]

  def index
    @billboards = Billboard.all
  end

  def show
    @artists = @billboard.artists

  end

  def edit
    
    render partial: "form"
  end

  def new
    @billboard = Billboard.new
    render partial: "form"
  end

  def create
    @billboard = Billboard.new(billboard_params)
    
    if @billboard.save
      redirect_to billboards_path
    else
      render :new
    end
  end


  def update
    if @billboard.update(billboard_params)
      redirect_to @billboard
    else
      render :edit
    end
  end

  def destroy
    @billboard.destroy
    redirect_to billboards_path
  end

  private 
    def set_billboard
      @billboard = Billboard.find(params[:id])
    end

    def set_artist
      @artist = Artist.new
    end

    def billboard_params
      params.require(:billboard).permit(:title, :artist_name, :song_name)
    end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist

  def index
    @song = Song.new
  end
  
  def create
    @song = @artist.songs.new(song_params)
    if @song.save
      redirect_to sub_artist_path(@artist.sub_id, @artist)
    else
      render :new
    end
  end

  # def destroy
  #   song = @artist.songs.find(params[:id])
  #   song.destroy
  #   redirect_to billboards_path

  # end

  private

    # def set_song
    #   @song = artist_songs_path(params[:artist_id])
    # end
    def set_artist
      @artist = artist.find(params[:artist_id])
    end

    def song_params
      params.require(:song).permit(:artist_name)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<h1><%= @artist.id ? 'Edit ' : 'Create ' %></h1>
<hr />
<%= form_for [@billboard, @artist] do |f| %>
  <%= f.label :artist_name %>
  <%= f.text_field :artist_name, required: true, autofocus: true %>
  <%= f.submit %>
 <% end %> 
  <br />
  <%= form_for [@billboard, @artist] do |f| %>
  <%= f.label :song_name %>
  <%= f.text_field :song_name, required: true, autofocus: true %>
<%= f.submit 'Update Song' %>
<% end %>

app/views/artists/index.html.erb
<h1><%= @billboard.title %></h1>
<h4>Click an artist to view more of their music</h4>
<p><%= link_to 'Add a new artist', new_billboard_artist_path(@billboard) %></p>
<ul>
  <% @artists.each do |artist| %>
    <li>
      <%= link_to artist.artist_name, [@billboard, artist] %>  
    </li>
  <% end %>
</ul>

app/views/artists/show.html.erb
<h1><%= @artist.artist_name %> </h1>
<p><%= @artist.song_name %></p>
<%= link_to 'Delete a Song', billboard_artist_path(@billboard), method: :delete %>
<%= link_to 'Add A Song', new_billboard_artist_path(@billboard) %>
<%= link_to 'Edit A Song', edit_billboard_artist_path(@billboard, @artist) %>
<%= link_to 'Remove A Song', billboard_artists_path, method: :delete %>
<%= link_to 'Back To Billboard', billboard_path %>

app/views/billboards/_form.html.erb
<h1><%= @billboard.id ? 'Edit Billboard' : 'Create Billboard' %></h1>
<hr />
<%= form_for @billboard do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true, autofocus: true %>

  <%= f.submit %>
<% end %>

app/views/billboards/index.html.erb
<div class="my-4 text-center text-lg-left">


<h1>Billboard Hot 100</h1>
  <%= link_to 'Create a new billboard', new_billboard_path %>
</div>


<div class="row text-center text-lg-left">

  <% @billboards.each do |billboard| %>
    <div class="col-lg-3 col-md-4 col-xs-6 card">
      <%= link_to billboard.title, billboard, :class => "d-block mb-4 h-15" %>
        <img class="img-fluid img-thumbnail" src="http://placehold.it/400x300" alt="">
    </div>
   
  <% end %>

</div>

app/views/billboards/show.html.erb
<h1><b><%= @billboard.title %></b></h1>
<h2>Click an artist to view more of their music</h2>
<hr />
<div class="container-fluid">
  <%= link_to 'New Artist', new_billboard_artist_path(@billboard) %> |
  <%= link_to 'Edit Billboard', edit_billboard_path(@billboard) %> |
  <%= link_to 'Delete Billboard', @billboard, method: :delete %> 
</div>
<hr />
<div class="container">
  <div class="row">
    <div class="col-6"><h3><b>Artist</b></h3></div>
    <div class="col-6"><h3><b>Song</b></h3></div>
  </div>
  <div class="row">
    <% @artists.each do |artist| %>
      <%= link_to artist.artist_name, [@billboard, artist], :class=> "col-6" %>   
    <% end %>
      <% @artists.each do |artist| %>
      <%= link_to artist.song_name, [@billboard, artist], :class=> "col-6" %> 
    <% end %>
  </div>
</div>
<hr />

<%= link_to 'Back', billboards_path %>

app/views/layouts/_navbar.html.erb
<nav>
  <ul>
   <li>
    <%= button_to 'Log Out', destroy_user_session_path, method: :delete %>
    <%= link_to 'Home', billboards_path %>
   </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billboard Group</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag    'bootstrap' %>
    <%= javascript_include_tag 'bootstrap' %>

  </head>

  <body class="container">
    <%= render 'layouts/navbar' %>
    <%= yield %>
  
  </body>
</html>

app/views/songs/_form.html.erb
<h1><%= @song.id ? 'Edit' : 'Create' %></h1>
<hr />
<%= form_for [@billboard, @artist] do |f| %>
  <%= f.label :song_name %>
  <%= f.text_field :song_name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<h1>Songs#index</h1>
<p>Find me in app/views/songs/index.html.erb</p>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<p>Find me in app/views/songs/show.html.erb</p>